/**
 * Storage interface contracts — implemented by @byo20/storage, consumed by @byo20/engine.
 *
 * Return types use `Row` (a plain record) as a temporary alias. Each will be replaced
 * with a concrete domain type during the schema implementation step, once Drizzle
 * infers the column shapes. TypeScript's structural typing means the implementation
 * will satisfy these interfaces as long as the shapes match — no explicit mapping needed.
 *
 * IDs are always `string` (UUID) — that part is typed correctly now.
 */

type Row = Record<string, unknown>

// ── IGameStateStore ────────────────────────────────────────────────────────────

/**
 * Typed query interface over byo20_server Postgres.
 * Follows the write-through pattern: callers must await the save before emitting
 * any WS events — no state change reaches clients without a committed DB write.
 */
export interface IGameStateStore {
  // Campaigns
  getCampaign(id: string): Promise<Row>
  saveCampaign(campaign: Row): Promise<void>

  // Characters
  getCharacter(id: string): Promise<Row>
  saveCharacter(character: Row): Promise<void>

  // Character campaign state
  getCharacterCampaignState(id: string): Promise<Row>
  saveCharacterCampaignState(state: Row): Promise<void>

  // Character classes (one row per class the character has levels in)
  getCharacterClasses(characterCampaignStateId: string): Promise<Row[]>
  saveCharacterClass(cls: Row): Promise<void>

  // Encounters
  getEncounter(id: string): Promise<Row>
  saveEncounter(encounter: Row): Promise<void>
  getActiveEncounter(campaignId: string): Promise<Row | null>

  // Initiative entries (one row per combatant)
  getInitiativeEntries(encounterId: string): Promise<Row[]>
  saveInitiativeEntry(entry: Row): Promise<void>

  // NPCs
  getNPC(id: string): Promise<Row>
  saveNPC(npc: Row): Promise<void>
  getNPCsInZone(campaignId: string, zoneId: string): Promise<Row[]>

  // Factions
  getFaction(id: string): Promise<Row>
  getFactionReputation(characterCampaignStateId: string, factionId: string): Promise<Row>
  saveFactionReputation(rep: Row): Promise<void>

  // Items
  getItems(campaignId: string, ownerId: string): Promise<Row[]>
  saveItem(item: Row): Promise<void>
  transferItem(itemId: string, newOwnerId: string, newOwnerType: string): Promise<void>

  // Quests
  getQuest(id: string): Promise<Row>
  saveQuest(quest: Row): Promise<void>
  getActiveQuests(campaignId: string): Promise<Row[]>

  // World zones
  getWorldZone(id: string): Promise<Row>
  saveWorldZone(zone: Row): Promise<void>

  // Append-only logs — these methods INSERT only, never UPDATE or DELETE
  appendEventLog(entry: Row): Promise<void>
  appendCombatLog(entry: Row): Promise<void>
  appendNPCDialogue(entry: Row): Promise<void>
  appendPartyChat(entry: Row): Promise<void>

  // Campaign snapshots (rolling window of 10, used for DM rollback)
  createSnapshot(campaignId: string, triggerType: string, triggerRef: string | null, label: string): Promise<void>
  getSnapshots(campaignId: string): Promise<Row[]>
  rollbackToSnapshot(snapshotId: string): Promise<void>

  // Sessions
  createSession(campaignId: string): Promise<Row>
  endSession(sessionId: string, summary: string): Promise<void>
}

// ── IVectorStore ───────────────────────────────────────────────────────────────

/**
 * Vector similarity search interface over pgvector columns.
 * All embeddings are 768-dimensional — generated by BYO20's bundled Ollama
 * instance using nomic-embed-text. The implementation never calls an LLM provider.
 */
export interface IVectorStore {
  // NPC memory — semantic recall for the NPC Specialist
  upsertMemory(memory: Row): Promise<void>
  queryMemories(npcId: string, queryEmbedding: number[], topK: number): Promise<Row[]>

  // Faction event memory — semantic recall for faction context
  upsertFactionEvent(event: Row): Promise<void>
  queryFactionEvents(factionId: string, queryEmbedding: number[], topK: number): Promise<Row[]>
}
