/**
 * memory.* schema — byo20_server
 *
 * pgvector tables for AI semantic recall.
 * Both tables store 768-dim embeddings generated by the bundled Ollama
 * instance using nomic-embed-text — never by the DM's LLM provider.
 * Queried with cosine similarity: <=> operator in raw SQL, or via
 * PostgresVectorStore which wraps the queries.
 */
import { boolean, integer, pgSchema, text, uuid } from 'drizzle-orm/pg-core'
import { npcs } from './world'
import { factions } from './world'
import { event_log } from './log'
import { quests } from './world'
import { vector } from '../vector-type'

/** Drizzle schema handle for the `memory` Postgres schema. */
export const memory = pgSchema('memory')

/**
 * NPC semantic memory — injected into NPC specialist context.
 * Decay is computed using created_at_clock vs. current world_clock.
 * Significance = true skips decay entirely (major plot beats, betrayals).
 */
export const npc_memories = memory.table('npc_memories', {
  id: uuid('id').primaryKey().defaultRandom(),
  npc_id: uuid('npc_id').notNull().references(() => npcs.id),
  event_log_id: uuid('event_log_id').notNull().references(() => event_log.id),
  quest_id: uuid('quest_id').references(() => quests.id), // nullable — quest-originated memories
  embedding: vector('embedding', 768).notNull(),
  sentiment: text('sentiment').notNull(),                  // positive | negative | neutral
  significance: boolean('significance').notNull().default(false),
  created_at_clock: integer('created_at_clock').notNull(), // world-clock minutes at creation
})

/**
 * Faction semantic memory — injected into faction/world context.
 * rep_delta tracks reputation change caused by this event for drift computation.
 */
export const faction_events = memory.table('faction_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  faction_id: uuid('faction_id').notNull().references(() => factions.id),
  event_log_id: uuid('event_log_id').notNull().references(() => event_log.id),
  quest_id: uuid('quest_id').references(() => quests.id),  // nullable
  embedding: vector('embedding', 768).notNull(),
  rep_delta: integer('rep_delta').notNull().default(0),
  created_at_clock: integer('created_at_clock').notNull(),
})
